apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-ms-hpa
  labels:
    app:nginx-ms
spec:
  minReplicas: 1
  maxReplicas: 10

  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 5
    type: Resource

  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-ms
