apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: vets
        image: mariokim/vet
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vets-svc
spec:
  selector:
    app: spring-petclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 32002
  type: LoadBalancer
