kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-jpasampleshop
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-04c883ba1e908867a
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jpasampleshop-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-jpasampleshop
  resources:
    requests:
      storage: 1Gi
---
