apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress-app
  annotations:
    kubernetes.io/change-cause: "Wordpress rolling update version latest from 5.8.1"
spec:
  replicas: 6
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.8.1
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          value: pressword
        - name: WORDPRESS_DB_USER
          value: pressword
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: WORDPRESS_DB_HOST
          value: wordpress.cfgwexy8deov.ap-northeast-2.rds.amazonaws.com
      nodeSelector:
        alpha.eksctl.io/nodegroup-name: WPNode
---
